import { AlertTriangle, ArrowRight, Box, Check, CheckCircle2, FileText, FolderCheck, ShieldCheck } from "lucide-react";
import type { RunRecord } from "../../api/types";
import { experimentPackageUrl, reportDownloadUrl } from "../../api/client";
import { comparableMetricSeries, coreMetricNames, formatMetricName, formatMetricValue, type ResearchViewModel } from "../researchViewModel";
import { PageHeader } from "./PageHeader";
import { LineChart } from "./MetricCharts";

type Props = { model: ResearchViewModel; run: RunRecord | null };
const bestMetrics = (model: ResearchViewModel) => {
  const core = coreMetricNames(model.experiments);
  return model.experiments.filter((item) => item.status === "completed").flatMap((experiment) => experiment.metrics.map((metric) => ({ ...metric, experiment: experiment.id }))).filter((item) => core.has(item.name)).slice(0, 5);
};

export function ResultsPage({ model, run }: Props) {
  const metrics = bestMetrics(model);
  const comparable = comparableMetricSeries(model.experiments);
  const score = model.reproducibility.length ? Math.round(model.reproducibility.filter((item) => item.ready).length / model.reproducibility.length * 100) : 0;
  const completed = Boolean(model.conclusion);
  const reportHref = run && model.reportAvailable ? reportDownloadUrl(run.id, "docx") : undefined;
  const packageHref = run && model.codePackageAvailable ? experimentPackageUrl(run.id) : undefined;
  const trace = [{ id: "Q1", label: "问题" }, ...(model.papers.length ? [{ id: `${model.papers.length} 篇`, label: "文献" }] : []), ...(model.selectedHypothesis ? [{ id: model.selectedHypothesis.id, label: "假设" }] : []), ...(model.experiments.length ? [{ id: `${model.experiments.length} 轮`, label: "实验" }] : []), ...(model.conclusion ? [{ id: "C1", label: "结论" }] : [])];
  return <div className="gew-page results-page"><section className="results-main">
    <PageHeader title="结果展示" english="Results" subtitle="只汇总当前研究真实生成的结论、指标、追踪与复现状态。" actions={<span className={`completion-state ${completed ? "complete" : "pending"}`}>{completed ? <CheckCircle2 size={16}/> : <AlertTriangle size={16}/>} {completed ? "报告已生成" : "研究进行中"}</span>}/>
    <div className="results-top-grid"><section className="final-conclusion"><header><ShieldCheck size={21}/><h2>最终结论</h2></header><p>{model.conclusion || "研究尚未生成最终结论。完成实验分析与报告步骤后，实际结论将在此显示。"}</p><div className="conclusion-support"><span><ShieldCheck size={24}/><b>{model.conclusion ? "结论已生成" : "等待结论"}</b></span><span><FileText size={23}/><b>{model.papers.length}</b><small>真实论文</small></span><span><FolderCheck size={23}/><b>{model.evidence.length}</b><small>证据项</small></span><span><CheckCircle2 size={23}/><b>{model.experiments.filter((item) => item.status === "completed").length}</b><small>成功实验</small></span></div></section><section className="conclusion-boundary"><header><AlertTriangle size={21}/><h2>结论边界</h2></header>{model.boundaries.length ? <ol>{model.boundaries.slice(0, 5).map((item, index) => <li key={index}><b>{index + 1}</b><span>{item}</span></li>)}</ol> : <div className="boundary-empty">当前研究尚未形成最终结论，因此暂不生成正式结论边界。</div>}</section></div>
    <div className="results-chart-grid"><section className="chart-card"><header><h2>关键结果</h2></header>{metrics.length ? <div className="key-metric-layout"><div className="metric-bars">{metrics.map((item) => <div key={`${item.experiment}-${item.name}`}><span title={`${item.experiment} · ${formatMetricName(item.name)}`}>{item.experiment} · {formatMetricName(item.name)}</span><div><i style={{ width: `${Math.min(100, Math.max(3, Math.abs(item.value) <= 1 ? Math.abs(item.value) * 100 : Math.abs(item.value)))}%` }}/></div><b>{formatMetricValue(item.value)}</b></div>)}</div></div> : <div className="chart-empty">当前没有成功实验指标。</div>}</section><section className="chart-card"><header><h2>性能演化</h2></header>{comparable ? <LineChart labels={comparable.rows.map((item) => item.id)} series={[{ name: formatMetricName(comparable.name), values: comparable.rows.map((item) => item.value), color: "#2454e6" }]} yLabel={formatMetricName(comparable.name)} metricDirection={comparable.direction}/> : <div className="chart-empty">至少需要两个具有相同主指标的有效科学实验，才能比较性能演化。</div>}</section></div>
    <div className="results-bottom-grid"><section className="research-trace"><header><h2>研究追踪</h2></header><div className="trace-flow">{trace.map((item, index) => <div key={item.label}><span className="trace-node"><b>{item.id}</b><small>{item.label}</small></span>{index < trace.length - 1 ? <i><ArrowRight size={18}/></i> : null}</div>)}</div><div className="trace-notes"><p><b>研究问题：</b>{model.question || "尚未定义"}</p><p>所有计数与节点均来自当前研究的真实产物。</p></div></section><section className="reproducibility"><header><h2>可复现性</h2></header><dl>{model.reproducibility.map((item) => <div key={item.label} className={item.ready ? "ready" : "missing"}><dt>{item.ready ? <Check size={15}/> : <AlertTriangle size={15}/>} {item.label}</dt><dd title={item.value}>{item.value}</dd></div>)}</dl><div className="repro-score"><span>当前完整度</span><b>{score}%</b></div></section><section className="report-contents"><header><h2>报告内容</h2></header>{model.reportSections.length ? <ol>{model.reportSections.map((section) => <li key={section}>{section.replace(/_/g, " ")}</li>)}</ol> : <p className="report-empty">当前研究尚未生成报告。</p>}<div className="fixed-export-actions">{reportHref ? <a className="button primary" href={reportHref}><FileText size={17}/>导出 Word 研究报告</a> : <button className="button primary" disabled title="需要先完成报告步骤"><FileText size={17}/>导出 Word 研究报告</button>}{packageHref ? <a className="button secondary" href={packageHref}><Box size={17}/>下载实验代码包</a> : <button className="button secondary" disabled title="当前研究没有真实实验代码"><Box size={17}/>下载实验代码包</button>}</div><small className="export-help">仅打包已保存的代码、配置、日志、指标、环境与研究产物；缺失内容不会伪造。</small></section></div>
  </section></div>;
}
